import type { Metadata } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${inter.variable} ${sourceSerif.variable} relative antialiased`}
      >
        <div className="relative mx-auto max-w-270">
          <Navbar />
          <div className="absolute left-0 h-screen w-px bg-linear-to-b from-neutral-300/50 via-neutral-300 to-transparent"></div>
          <div className="absolute right-0 h-screen w-px bg-linear-to-b from-neutral-300/50 via-neutral-300 to-transparent"></div>
          {children}
        </div>
      </body>
    </html>
  );
}
